//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prilozenie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telephone_subscribers
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int Phone { get; set; }
        public string Email { get; set; }
        public int id_City { get; set; }
        public int id_Street { get; set; }
        public int House { get; set; }
        public int Kvartira { get; set; }
    
        public virtual City City { get; set; }
        public virtual Street Street { get; set; }
    }
}
